### PR TITLE
adding shebang to head of ./start.sh

### PR DESCRIPTION
**Pull request by noqcks**
I was unable to execute this properly on my mac without the shebang.

```
-> ./start.sh
Failed to execute process './start.sh'. Reason:
exec: Exec format error
The file './start.sh' is marked as an executable but could not be run by the operating system.
```

### CODE REVIEW

**Comment by brannondorsey** [comment]
Cheers! Any any reason to chose `sh` as the shell over `bash`?

**Comment by brannondorsey** [comment]
@mosspassion I'm pretty sure this is why you were having issues with the Fish shell.

**Comment by mosspassion** [comment]
@brannondorsey thanks b!

**Comment by noqcks** [comment]
none of the bash features are used here afaik. `sh` is more widely supported

**Comment by brannondorsey** [comment]
@noqcks makes sense. I always use bash but that is a good argument. Thanks for updating :)

**Pull request merged**
